backend:
  name: git-gateway
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: XXXX
    api_key: XXXX

locale: es

collections:
  - name: "site-config"
    label: "Configuración del Sitio"
    files:
      - label: "Configuración General"
        name: "general"
        file: "src/_data/site.json"
        fields:
          - {label: "Nombre del Sitio", name: "name", widget: "string"}
          - {label: "Descripción", name: "description", widget: "text"}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "Email de Contacto", name: "email", widget: "string"}
          - {label: "Teléfono", name: "phone", widget: "string"}
          - {label: "Dirección", name: "address", widget: "text"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Favicon", name: "favicon", widget: "image"}
          - label: "Redes Sociales"
            name: "social"
            widget: "object"
            fields:
              - {label: "Facebook", name: "facebook", widget: "string"}
              - {label: "Twitter", name: "twitter", widget: "string"}
              - {label: "LinkedIn", name: "linkedin", widget: "string"}
              - {label: "Instagram", name: "instagram", widget: "string"}
              - {label: "YouTube", name: "youtube", widget: "string"}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - {label: "Google Analytics", name: "googleAnalytics", widget: "string"}
              - {label: "Google Tag Manager", name: "googleTagManager", widget: "string"}
              - {label: "Meta Keywords", name: "metaKeywords", widget: "string"}
              - {label: "Meta Description", name: "metaDescription", widget: "text"}

  - name: "paginas-servicios"
    label: "Páginas de Servicios"
    folder: "src/pages"
    create: false
    slug: "{{slug}}"
    filter:
      field: "layout"
      value: "pages/_servicios.njk"
    fields:
      - {label: "Layout", name: "layout", widget: "string", default: "pages/_servicios.njk"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Meta title", name: "metaTitle", widget: "string"}
      - {label: "Meta description", name: "metaDescription", widget: "string"}
      - {label: "Meta keywords", name: "metaKeywords", widget: "string"}
      - {label: "Meta robots", name: "metaRobots", widget: "string", default: "index, follow"}
      - {label: "Tags", name: "tags", widget: "list", default: ["pages"]}
      - {label: "Sección", name: "seccion", widget: "string"}
      - {label: "Prioridad", name: "priority", widget: "number"}
      - {label: "Hero Description", name: "hero_description", widget: "string"}
      - {label: "Hero Title", name: "hero_title", widget: "string"}
      - {label: "Hero Button", name: "hero_btn", widget: "string"}
      - {label: "Home Image", name: "home_image", widget: "image"}
      - {label: "Intro Benefits Subtitle", name: "introbenefits2_subtitle", widget: "string"}
      - {label: "Intro Benefits Content", name: "introbenefits2_content", widget: "text"}
      - {label: "Intro Benefits Title", name: "introbenefits_title", widget: "string"}
      - {label: "Intro Benefits Subtitle 2", name: "introbenefits_subtitle", widget: "string"}
      - {label: "Benefit 1 Title", name: "introbenefits_1title", widget: "string"}
      - {label: "Benefit 1 Description", name: "introbenefits_1description", widget: "text"}
      - {label: "Benefit 2 Title", name: "introbenefits_2title", widget: "string"}
      - {label: "Benefit 2 Description", name: "introbenefits_2description", widget: "text"}
      - {label: "Benefit 3 Title", name: "introbenefits_3title", widget: "string"}
      - {label: "Benefit 3 Description", name: "introbenefits_3description", widget: "text"}
      - {label: "Benefit 4 Title", name: "introbenefits_4title", widget: "string"}
      - {label: "Benefit 4 Description", name: "introbenefits_4description", widget: "text"}
      - {label: "Benefit 5 Title", name: "introbenefits_5title", widget: "string"}
      - {label: "Benefit 5 Description", name: "introbenefits_5description", widget: "text"}
      - {label: "Why Title Subtitle", name: "whytitle1_subtitle", widget: "text"}
      - {label: "Why Title Description", name: "whytitle1_description", widget: "string"}
      - {label: "Content Foto Img", name: "content_foto_img", widget: "image"}
      - {label: "Content Foto Img 2", name: "content_foto_img_2", widget: "image"}
      - {label: "Intro Benefits Class", name: "introbenefits_class", widget: "string", default: "bg-dark"}
      - {label: "Box Img Title", name: "box_img_title", widget: "string"}
      - {label: "Box Img Description", name: "box_img_description", widget: "text"}
      - {label: "Box Img Img", name: "box_img_img", widget: "image"}
      - {label: "Servicios Title", name: "servicios", widget: "string"}
      - {label: "Servicio 1 Title", name: "servicio1_title", widget: "string"}
      - {label: "Servicio 1 Content", name: "servicio1_content", widget: "text"}
      - {label: "Servicio 1 Img", name: "servicio1_img", widget: "string"}
      - {label: "Servicio 2 Title", name: "servicio2_title", widget: "string"}
      - {label: "Servicio 2 Content", name: "servicio2_content", widget: "text"}
      - {label: "Servicio 2 Img", name: "servicio2_img", widget: "string"}
      - {label: "Servicio 3 Title", name: "servicio3_title", widget: "string"}
      - {label: "Servicio 3 Content", name: "servicio3_content", widget: "text"}
      - {label: "Servicio 3 Img", name: "servicio3_img", widget: "string"}
      - {label: "Servicio 4 Title", name: "servicio4_title", widget: "string"}
      - {label: "Servicio 4 Content", name: "servicio4_content", widget: "text"}
      - {label: "Servicio 4 Img", name: "servicio4_img", widget: "string"}
      - {label: "Contacta 4 Title", name: "contacta_4_title", widget: "string"}
      - {label: "Contacta 4 Subtitle", name: "contacta_4_subtitle", widget: "string"}

  - name: "paginas-contacto"
    label: "Páginas de Contacto"
    folder: "src/pages"
    create: false
    slug: "{{slug}}"
    filter:
      field: "layout"
      value: "pages/_contacta.njk"
    fields:
      - {label: "Layout", name: "layout", widget: "string", default: "pages/_contacta.njk"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Meta title", name: "metaTitle", widget: "string"}
      - {label: "Meta description", name: "metaDescription", widget: "string"}
      - {label: "Meta keywords", name: "metaKeywords", widget: "string"}
      - {label: "Meta robots", name: "metaRobots", widget: "string", default: "index, follow"}
      - {label: "Tags", name: "tags", widget: "list", default: ["pages"]}
      - {label: "Sección", name: "seccion", widget: "string"}
      - {label: "Prioridad", name: "priority", widget: "number"}
      - {label: "Hero Description", name: "hero_description", widget: "string"}
      - {label: "Hero Title", name: "hero_title", widget: "string"}
      - {label: "Hero Button", name: "hero_btn", widget: "string"}
      - {label: "Home Image", name: "home_image", widget: "image"}
      - {label: "Contacta Title", name: "contacta_title", widget: "string"}
      - {label: "Contacta Subtitle", name: "contacta_subtitle", widget: "string"}
      - {label: "Contacta 5 Title", name: "contacta_5_title", widget: "string"}
      - {label: "Contacta 5 Subtitle", name: "contacta_5_subtitle", widget: "string"}
      - {label: "Contacta Map", name: "contacta_map", widget: "text"}
      - {label: "Banner Button", name: "banner_button", widget: "string"}
      - {label: "Dirección", name: "direction", widget: "string"}
      - {label: "Teléfono", name: "telefono", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}

  - name: "paginas-seo"
    label: "Páginas SEO"
    folder: "src/pages"
    create: false
    slug: "{{slug}}"
    filter:
      field: "layout"
      value: "../templates/_siteseo_titles.njk"
    fields:
      - {label: "Layout", name: "layout", widget: "string", default: "../templates/_siteseo_titles.njk"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Why Title 1", name: "whytitle1", widget: "text"}
      - {label: "Why Title 2", name: "whytitle2", widget: "text"}
      - {label: "Why Title 3", name: "whytitle3", widget: "text"}
      - {label: "Meta Title", name: "metaTitle", widget: "string"}
      - {label: "Meta Description", name: "metaDescription", widget: "text"}
      - {label: "Meta Keywords", name: "metaKeywords", widget: "string"}
      - {label: "Meta Robots", name: "metaRobots", widget: "string", default: "index, follow"}

  - name: "paginas-generales"
    label: "Páginas Generales"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "select"
        options:
          - {label: "Página por defecto", value: "pages/_default.njk"}
          - {label: "Página de servicios", value: "pages/_servicios.njk"}
          - {label: "Página de contacto", value: "pages/_contacta.njk"}
          - {label: "Página SEO", value: "../templates/_siteseo_titles.njk"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Meta title", name: "metaTitle", widget: "string"}
      - {label: "Meta description", name: "metaDescription", widget: "string"}
      - {label: "Meta keywords", name: "metaKeywords", widget: "string"}
      - {label: "Meta robots", name: "metaRobots", widget: "string", default: "index, follow"}
      - {label: "Tags", name: "tags", widget: "list", default: ["pages"]}
      - {label: "Sección", name: "seccion", widget: "string"}
      - {label: "Prioridad", name: "priority", widget: "number"}
      - {label: "Hero Description", name: "hero_description", widget: "string"}
      - {label: "Hero Title", name: "hero_title", widget: "string"}
      - {label: "Hero Button", name: "hero_btn", widget: "string"}
      - {label: "Home Image", name: "home_image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Why Title 1", name: "whytitle1", widget: "text"}
      - {label: "Why Title 2", name: "whytitle2", widget: "text"}
      - {label: "Why Title 3", name: "whytitle3", widget: "text"}
      - {label: "Why Title 1 Subtitle", name: "whytitle1_subtitle", widget: "text"}
      - {label: "Why Title 1 Description", name: "whytitle1_description", widget: "string"}
      - {label: "Contacta Title", name: "contacta_title", widget: "string"}
      - {label: "Contacta Subtitle", name: "contacta_subtitle", widget: "string"}
      - {label: "Contacta 5 Title", name: "contacta_5_title", widget: "string"}
      - {label: "Contacta 5 Subtitle", name: "contacta_5_subtitle", widget: "string"}
      - {label: "Contacta Map", name: "contacta_map", widget: "text"}
      - {label: "Banner Button", name: "banner_button", widget: "string"}
      - {label: "Dirección", name: "direction", widget: "string"}
      - {label: "Teléfono", name: "telefono", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "pages"
    label: "Páginas (Legacy)"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "string", default: "pages/_default.njk"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Meta title", name: "metaTitle", widget: "string"}
      - {label: "Meta description", name: "metaDescription", widget: "string"}
      - {label: "Meta keywords", name: "metaKeywords", widget: "string"}
      - {label: "Meta robots", name: "metaRobots", widget: "string", default: "index, follow"}
      - {label: "Tags", name: "tags", widget: "list", default: ["pages"]}
      - {label: "Sección", name: "seccion", widget: "string"}
      - {label: "Prioridad", name: "priority", widget: "number"}
      - {label: "Hero Description", name: "hero_description", widget: "string"}
      - {label: "Hero Title", name: "hero_title", widget: "string"}
      - {label: "Hero Button", name: "hero_btn", widget: "string"}
      - {label: "Home Image", name: "home_image", widget: "image"}
      - {label: "Contacta Title", name: "contacta_title", widget: "string"}
      - {label: "Contacta Subtitle", name: "contacta_subtitle", widget: "string"}
      - {label: "Contacta 5 Title", name: "contacta_5_title", widget: "string"}
      - {label: "Contacta 5 Subtitle", name: "contacta_5_subtitle", widget: "string"}
      - {label: "Contacta Map", name: "contacta_map", widget: "text"}
      - {label: "Banner Button", name: "banner_button", widget: "string"}
      - {label: "Dirección", name: "direction", widget: "string"}
      - {label: "Teléfono", name: "telefono", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "servicios"
    label: "Servicios"
    folder: "src/servicios"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "string", default: "pages/_servicio.njk"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Meta title", name: "metaTitle", widget: "string"}
      - {label: "Meta description", name: "metaDescription", widget: "string"}
      - {label: "Meta keywords", name: "metaKeywords", widget: "string"}
      - {label: "Meta robots", name: "metaRobots", widget: "string", default: "index, follow"}
      - {label: "Tags", name: "tags", widget: "list", default: ["servicios"]}
      - {label: "Sección", name: "seccion", widget: "string"}
      - {label: "Prioridad", name: "priority", widget: "number"}
      - {label: "Hero Description", name: "hero_description", widget: "string"}
      - {label: "Hero Title", name: "hero_title", widget: "string"}
      - {label: "Hero Button", name: "hero_btn", widget: "string"}
      - {label: "Hero Image", name: "hero_image", widget: "image"}
      - {label: "Título del Servicio", name: "service_title", widget: "string"}
      - {label: "Subtítulo del Servicio", name: "service_subtitle", widget: "string"}
      - {label: "Descripción Corta", name: "service_description", widget: "text"}
      - {label: "Imagen Principal", name: "service_image", widget: "image"}
      - {label: "Icono", name: "service_icon", widget: "image"}
      - label: "Características"
        name: "features"
        widget: "list"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Descripción", name: "description", widget: "text"}
          - {label: "Icono", name: "icon", widget: "image"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Moneda", name: "currency", widget: "string", default: "€"}
      - {label: "Período", name: "period", widget: "string", default: "mes"}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog"
    folder: "src/es/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Meta title", name: "metaTitle", widget: "string"}
      - {label: "Meta description", name: "metaDescription", widget: "string"}
      - {label: "Meta keywords", name: "metaKeywords", widget: "string"}
      - {label: "Meta robots", name: "metaRobots", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", required: false}
      - {label: "Category", name: "category", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"], required: false}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Image alt", name: "imageAlt", widget: "string", required: false}
      - {label: "Twitter", name: "social_twitter", widget: "string", required: false}
      - {label: "LinkedIn", name: "social_linkedin", widget: "string", required: false}
      - {label: "WhatsApp", name: "social_whatsapp", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
